services:
  - type: web
    name: mausam-ai
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_OPENWEATHER_API_KEY
        sync: false
