services:
  - type: web
    name: mausam-ai
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WEATHER_API_KEY
        sync: false  # This needs to be set in the Render dashboard
      - key: VITE_API_BASE_URL
        value: https://api.openweathermap.org/data/2.5
      - key: VITE_DEFAULT_CITY
        value: New Delhi
